from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(698, 567)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
		self.Tabs.setObjectName("Tabs")
		self.tab = QtWidgets.QWidget()
		self.tab.setObjectName("tab")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.InsultTextBox = QtWidgets.QTextBrowser(self.tab)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(1)
		sizePolicy.setHeightForWidth(self.InsultTextBox.sizePolicy().hasHeightForWidth())
		self.InsultTextBox.setSizePolicy(sizePolicy)
		self.InsultTextBox.setObjectName("InsultTextBox")
		self.verticalLayout_2.addWidget(self.InsultTextBox)
		self.label_2 = QtWidgets.QLabel(self.tab)
		self.label_2.setObjectName("label_2")
		self.verticalLayout_2.addWidget(self.label_2)
		spacerItem = QtWidgets.QSpacerItem(20, 245, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
		self.verticalLayout_2.addItem(spacerItem)
		self.label = QtWidgets.QLabel(self.tab)
		font = QtGui.QFont()
		font.setPointSize(14)
		font.setBold(False)
		font.setItalic(True)
		self.label.setFont(font)
		self.label.setScaledContents(False)
		self.label.setObjectName("label")
		self.verticalLayout_2.addWidget(self.label)
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		self.ShakespeareButton = QtWidgets.QRadioButton(self.tab)
		self.ShakespeareButton.setObjectName("ShakespeareButton")
		self.horizontalLayout_5.addWidget(self.ShakespeareButton)
		self.ScotButton = QtWidgets.QRadioButton(self.tab)
		self.ScotButton.setObjectName("ScotButton")
		self.horizontalLayout_5.addWidget(self.ScotButton)
		self.YeOldButton = QtWidgets.QRadioButton(self.tab)
		self.YeOldButton.setObjectName("YeOldButton")
		self.horizontalLayout_5.addWidget(self.YeOldButton)
		self.SciFiButton = QtWidgets.QRadioButton(self.tab)
		self.SciFiButton.setObjectName("SciFiButton")
		self.horizontalLayout_5.addWidget(self.SciFiButton)
		self.AyeButton = QtWidgets.QRadioButton(self.tab)
		self.AyeButton.setObjectName("AyeButton")
		self.horizontalLayout_5.addWidget(self.AyeButton)
		self.horizontalLayout_5.setStretch(0, 1)
		self.horizontalLayout_5.setStretch(1, 1)
		self.horizontalLayout_5.setStretch(2, 1)
		self.horizontalLayout_5.setStretch(3, 1)
		self.horizontalLayout_5.setStretch(4, 1)
		self.verticalLayout_2.addLayout(self.horizontalLayout_5)
		self.InsultMeButton = QtWidgets.QPushButton(self.tab)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(1)
		sizePolicy.setHeightForWidth(self.InsultMeButton.sizePolicy().hasHeightForWidth())
		self.InsultMeButton.setSizePolicy(sizePolicy)
		self.InsultMeButton.setObjectName("InsultMeButton")
		self.verticalLayout_2.addWidget(self.InsultMeButton)
		self.Tabs.addTab(self.tab, "")
		self.tab_2 = QtWidgets.QWidget()
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(1)
		sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
		self.tab_2.setSizePolicy(sizePolicy)
		self.tab_2.setObjectName("tab_2")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
		self.verticalLayout.setObjectName("verticalLayout")
		self.ImageView = QtWidgets.QGraphicsView(self.tab_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(94)
		sizePolicy.setHeightForWidth(self.ImageView.sizePolicy().hasHeightForWidth())
		self.ImageView.setSizePolicy(sizePolicy)
		self.ImageView.setMinimumSize(QtCore.QSize(200, 0))
		self.ImageView.setObjectName("ImageView")
		self.verticalLayout.addWidget(self.ImageView)
		self.formLayout = QtWidgets.QFormLayout()
		self.formLayout.setObjectName("formLayout")
		self.verticalLayout.addLayout(self.formLayout)
		self.ImageSearchBox = QtWidgets.QTextEdit(self.tab_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(3)
		sizePolicy.setHeightForWidth(self.ImageSearchBox.sizePolicy().hasHeightForWidth())
		self.ImageSearchBox.setSizePolicy(sizePolicy)
		self.ImageSearchBox.setObjectName("ImageSearchBox")
		self.verticalLayout.addWidget(self.ImageSearchBox)
		self.ImageSearchButton = QtWidgets.QPushButton(self.tab_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(1)
		sizePolicy.setHeightForWidth(self.ImageSearchButton.sizePolicy().hasHeightForWidth())
		self.ImageSearchButton.setSizePolicy(sizePolicy)
		self.ImageSearchButton.setObjectName("ImageSearchButton")
		self.verticalLayout.addWidget(self.ImageSearchButton)
		self.Tabs.addTab(self.tab_2, "")
		self.horizontalLayout.addWidget(self.Tabs)
		MainWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(MainWindow)
		self.Tabs.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.label_2.setText(_translate("MainWindow", "All the insults were gathered from https://fungenerators.com/api/taunt."))
		self.label.setText(_translate("MainWindow", "Choose an insult category"))
		self.ShakespeareButton.setText(_translate("MainWindow", "Shakespeare"))
		self.ScotButton.setText(_translate("MainWindow", "Scottish"))
		self.YeOldButton.setText(_translate("MainWindow", "Medieval"))
		self.SciFiButton.setText(_translate("MainWindow", "SciFi"))
		self.AyeButton.setText(_translate("MainWindow", "Pirate"))
		self.InsultMeButton.setText(_translate("MainWindow", "Insult Me"))
		self.Tabs.setTabText(self.Tabs.indexOf(self.tab), _translate("MainWindow", "Insults"))
		self.ImageSearchButton.setText(_translate("MainWindow", "Search"))
		self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), _translate("MainWindow", "Images"))
