from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("Random Stuff I guess")
		MainWindow.resize(698, 567)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
		self.Tabs.setObjectName("Tabs")
		self.tab = QtWidgets.QWidget()
		self.tab.setObjectName("tab")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.textBrowser = QtWidgets.QTextBrowser(self.tab)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(1)
		sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
		self.textBrowser.setSizePolicy(sizePolicy)
		self.textBrowser.setObjectName("textBrowser")
		self.verticalLayout_2.addWidget(self.textBrowser)
		spacerItem = QtWidgets.QSpacerItem(20, 245, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		self.verticalLayout_2.addItem(spacerItem)
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		self.radioButton_2 = QtWidgets.QRadioButton(self.tab)
		self.radioButton_2.setObjectName("radioButton_2")
		self.horizontalLayout_5.addWidget(self.radioButton_2)
		self.radioButton_3 = QtWidgets.QRadioButton(self.tab)
		self.radioButton_3.setObjectName("radioButton_3")
		self.horizontalLayout_5.addWidget(self.radioButton_3)
		self.radioButton = QtWidgets.QRadioButton(self.tab)
		self.radioButton.setObjectName("radioButton")
		self.horizontalLayout_5.addWidget(self.radioButton)
		self.radioButton_5 = QtWidgets.QRadioButton(self.tab)
		self.radioButton_5.setObjectName("radioButton_5")
		self.horizontalLayout_5.addWidget(self.radioButton_5)
		self.radioButton_4 = QtWidgets.QRadioButton(self.tab)
		self.radioButton_4.setObjectName("radioButton_4")
		self.horizontalLayout_5.addWidget(self.radioButton_4)
		self.horizontalLayout_5.setStretch(0, 1)
		self.horizontalLayout_5.setStretch(1, 1)
		self.horizontalLayout_5.setStretch(2, 1)
		self.horizontalLayout_5.setStretch(3, 1)
		self.horizontalLayout_5.setStretch(4, 1)
		self.verticalLayout_2.addLayout(self.horizontalLayout_5)
		self.pushButton = QtWidgets.QPushButton(self.tab)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(1)
		sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
		self.pushButton.setSizePolicy(sizePolicy)
		self.pushButton.setObjectName("pushButton")
		self.verticalLayout_2.addWidget(self.pushButton)
		self.Tabs.addTab(self.tab, "")
		self.tab_2 = QtWidgets.QWidget()
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(1)
		sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
		self.tab_2.setSizePolicy(sizePolicy)
		self.tab_2.setObjectName("tab_2")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
		self.verticalLayout.setObjectName("verticalLayout")
		self.ImageView = QtWidgets.QGraphicsView(self.tab_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(94)
		sizePolicy.setHeightForWidth(self.ImageView.sizePolicy().hasHeightForWidth())
		self.ImageView.setSizePolicy(sizePolicy)
		self.ImageView.setMinimumSize(QtCore.QSize(200, 0))
		self.ImageView.setObjectName("ImageView")
		self.verticalLayout.addWidget(self.ImageView)
		self.formLayout = QtWidgets.QFormLayout()
		self.formLayout.setObjectName("formLayout")
		self.verticalLayout.addLayout(self.formLayout)
		self.ImageSearchBox = QtWidgets.QTextEdit(self.tab_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(3)
		sizePolicy.setHeightForWidth(self.ImageSearchBox.sizePolicy().hasHeightForWidth())
		self.ImageSearchBox.setSizePolicy(sizePolicy)
		self.ImageSearchBox.setObjectName("ImageSearchBox")
		self.verticalLayout.addWidget(self.ImageSearchBox)
		self.ImageSearchButton = QtWidgets.QPushButton(self.tab_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(1)
		sizePolicy.setHeightForWidth(self.ImageSearchButton.sizePolicy().hasHeightForWidth())
		self.ImageSearchButton.setSizePolicy(sizePolicy)
		self.ImageSearchButton.setObjectName("ImageSearchButton")
		self.verticalLayout.addWidget(self.ImageSearchButton)
		self.Tabs.addTab(self.tab_2, "")
		self.horizontalLayout.addWidget(self.Tabs)
		MainWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(MainWindow)
		self.Tabs.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.radioButton_2.setText(_translate("MainWindow", "Shakespear"))
		self.radioButton_3.setText(_translate("MainWindow", "Scottish"))
		self.radioButton.setText(_translate("MainWindow", "Medieval"))
		self.radioButton_5.setText(_translate("MainWindow", "SciFi"))
		self.radioButton_4.setText(_translate("MainWindow", "Pirate"))
		self.pushButton.setText(_translate("MainWindow", "Insult Me"))
		self.Tabs.setTabText(self.Tabs.indexOf(self.tab), _translate("MainWindow", "Insults"))
		self.ImageSearchButton.setText(_translate("MainWindow", "Search"))
		self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), _translate("MainWindow", "Images"))
